### ISSUE TITLE
Asking about calling auth service from bookstore

### ISSUE THREAD

**Issue by quanhua92** [thebracket/ArdanRustService#1]
Hi,
Thank you for your great project. I don't understand the auth_layers so I want to ask if you can help me with the line
https://github.com/thebracket/ArdanRustService/blob/9b2e347ec9b777726c2ad746bc3c541e0f9ac131/no_workspace/deploy_bookstore/src/bookstore/mod.rs#L20
In the bookstore router, there isn't any call to Extension AuthDb so how the `require_token` can resolve the AuthDb Extension parameter to get the id from the token?
Thanks.

**Comment by thebracket** [comment]
I'm taking a look now - from looking on my phone, it looks like we may have pushed an older version of that example. I'll be in the office (with the original files) a little later today to check that and get it updated if necessary. Thanks!

**Comment by thebracket** [comment]
Ok, the correct version of the files is up now. It adds some JavaScript to the book admin, and a cross-service call for token validation. That makes it fit with the class text, too. Sorry about that!

**Comment by quanhua92** [comment]
Thank you very much. It is obvious now.
